### ISSUE TITLE
Throwing error while running the sitemap URL

### ISSUE THREAD

**Issue by satheesh-mallow** [pecotamic/sitemap#10]
Hello Team, 

We have tried to integrate the plugin, but it throwing the below attached error.

<img width="1409" alt="Screenshot 2021-06-14 at 12 35 52 PM" src="https://user-images.githubusercontent.com/14173227/121852568-4d4b9500-cd0d-11eb-8b0b-c520c5e355b7.png">

**Comment by werner-freytag** [comment]
There seems to be some output on your server before the rendering of the sitemap starts. Please verify your server. This problem does not occur otherwise.
