### ISSUE TITLE
Got error isAbsoluteUrl() must be of the type string,

### ISSUE THREAD

**Issue by koyanyaroo** [pecotamic/sitemap#11]
Hi,

Thanks for your amazing addons, I really loved that.

Lately I got an issue while try to accessing the `/sitemap.xml` 

>Argument 1 passed to Pecotamic\Sitemap\Models\Sitemap::isAbsoluteUrl() must be of the type string, null given, called in

here's some details about my environment
PHP Version:  7.4.20 
Statamic version: 3.1.25
pecotamic/sitemap version: 1.2.3

without any custom configuration or view

but after I change on `vendor/pecotamic/sitemap/src/Models/Sitemap.php` 

```php
 protected static function isAbsoluteUrl(string $url): bool
    {
        return preg_match('#^https?://#', $url);
    }
```
become 
```php
 protected static function isAbsoluteUrl(?string $url): bool
    {
        return preg_match('#^https?://#', $url);
    }
```

the error disappear.

just wondering if the tweak are save or wont making any other breakage under the hood?

Thank you

**Comment by werner-freytag** [comment]
Fixed in 1.2.4
