### ISSUE TITLE
Unable to cache config because of this Addon

### ISSUE THREAD

**Issue by Rkallenkoot** [pecotamic/sitemap#12]
Because of the filter config in this addon, we're unable to cache the config. Any idea's if there's another way to get the functionality without using a closure in configs?

**Comment by werner-freytag** [comment]
If you don't need the filter callback, you can simply set it to `null`:

```php
...

'filter' => null,

...
```

Just out of interest: How and why do you cache the config?

**Comment by Utakka** [comment]
We do config caching, too. To gain a little bit performance:
https://laravel.com/docs/8.x/configuration#configuration-caching

Would be great if the filter and properties settings were set to null by default.

**Comment by werner-freytag** [comment]
I've changed the default value now.
