### ISSUE TITLE
Multisite problem: only origin language URLs are generated

### ISSUE THREAD

**Issue by gpluess** [pecotamic/sitemap#17]
Great plugin, thanks!

I've just installed it in a multisite Statamic project and noticed, that only URLs for the origin language are created in the sitemap.xml file.

My sites.php config file looks like this:
```
'sites' => [

    'en' => [
        'name' => 'English',
        'locale' => 'en_US',
        'url' => '/en/',
    ],

    'de' => [
        'name' => 'Deutsch',
        'locale' => 'de_DE',
        'url' => '/de/',
    ],

],
```

Not sure if I missed anything? When I change the order in my sites.php config file, only "de" URLs are shown in the sitemap.xml

Any help is greatly appreciated!

**Comment by werner-freytag** [comment]
Sorry for the long delay. I've just released an update which adds multi-site support. There is a separate sitemap for each site.
