### ISSUE TITLE
Issue with Statamic 3.3

### ISSUE THREAD

**Issue by MrMooky** [pecotamic/sitemap#18]
I'm aware that Statamic 3.3 was just released, but I'd like to point out this error when trying to open my `sitemap.xml` file:

> production.ERROR: Pecotamic\Sitemap\Models\SitemapEntry::__construct(): Argument #2 ($lastmod) must be of type DateTime, Statamic\Fields\Value given, called in /home/webapps/featureshift/releases/20220315162345/vendor/pecotamic/sitemap/src/Models/Sitemap.php on line 52

**Comment by werner-freytag** [comment]
Thank you for your bug report!

I've fixed this in release 1.2.8
