### ISSUE TITLE
Sitemap not showing up in production

### ISSUE THREAD

**Issue by connor11528** [pecotamic/sitemap#4]
Hi there, I'm hosting my site on Netlify through the SSG package. I've installed this package and the sitemap comes up fine on my local like: http://connorleech.test/sitemap.xml but unfortunately does not show in production at https://www.connorleech.info/sitemap.xml. Is there some config that I need to add or can check to make sure my sitemap gets deployed to my production site?

**Comment by connor11528** [comment]
My site is hosted on Netlify. I have `APP_URL=https://www.connorleech.info` but sitemap is still not present in productions. Any ideas how I can generate a sitemap for my site?

**Comment by werner-freytag** [comment]
Looks like `composer.json` or `composer.lock` where not deployed or `composer install` has not been run. Have you been able to fix this issue?

**Comment by connor11528** [comment]
I ended up using the Netlify sitemap plugin to generate a sitemap for my Netlify site :) https://github.com/netlify-labs/netlify-plugin-sitemap

**Comment by connor11528** [comment]
Since it's a static site there isn't really a PHP server. Maybe using this package with Statamic SSG isn't a good use case 🤷 we can close this issue..

**Comment by werner-freytag** [comment]
Thanks for your feedback!
