### ISSUE TITLE
Connection error after instalation

### ISSUE THREAD

**Issue by miloslavkostir** [pecotamic/sitemap#5]
Hi

there is a connection error after composer instalation:

```
> @php artisan statamic:install --ansi
GuzzleHttp\Exception\ConnectException 
Connection refused for URI https://statamic.com/api/v1/marketplace/packages/pecotamic/sitemap/1.1.0
```

**Comment by werner-freytag** [comment]
I'm not sure, if this is related to this plugin or to the statamic marketplace. Where does this problem occur?

**Comment by miloslavkostir** [comment]
Probably that was a problem in the statamic marketplace. The error no longer occurs.
Thanks
