### ISSUE TITLE
Homepage showing multiple times

### ISSUE THREAD

**Issue by taylorcammack** [pecotamic/sitemap#6]
Homepage showing up multiple times in dev and production, in this case, 88 times. Not sure about any correlations related to the number. I have 40 total entries in the Pages collection... idk 🤷🏼‍♂️

![Screen Shot 2021-03-26 at 9 58 18 AM](https://user-images.githubusercontent.com/2514935/112651140-1a82b680-8e1a-11eb-9981-04bb0c6d78ef.png)

### Installed Addons

**Statamic** 3.1.1 Pro
**Laravel** 7.30.4
**PHP** 7.4.15
**aryehraber/statamic-captcha** 1.3.0
**pecotamic/sitemap** 1.2.0
**rias/statamic-data-import** 1.1.2
**spatie/statamic-algolia-places** 1.1.0
**spatie/statamic-responsive-images** 2.5.3

**Comment by werner-freytag** [comment]
Did you change some settings in the config?

**Comment by taylorcammack** [comment]
No changes. Hadn't even run the command to copy the default config, although I just did to see if that would affect anything. No dice.

**Comment by werner-freytag** [comment]
The sitemap uses the augmented value "absolute_url". Is this value overwritten somewhere?

Maybe a problem due to another plugin. Have you tried to deactivate them as a test?

**Comment by taylorcammack** [comment]
Went through and de-activated everything one-by-one and still getting the same results

**Comment by werner-freytag** [comment]
Did you clear the cache between the attempts? (using `php artisan cache:clear`)

Are there possibly missing entries in the sitemap that are incorrectly output as root path?

**Comment by zgambs** [comment]
I am having the same issue on a site that was migrated from V2 to V3. All I did was run `composer require pecotamic/sitemap` and clear caches and I am having this same issue. I havent changed or customized anything.

**Comment by werner-freytag** [comment]
@zgambs Can you tell me then if there are possibly missing entries in the sitemap that are incorrectly output as root path?

**Comment by werner-freytag** [comment]
Please tell me, if this still occurs in release 1.2.2
