### ISSUE TITLE
Error after upgrading to 1.2.0

### ISSUE THREAD

**Issue by sarunaslite** [pecotamic/sitemap#7]
Argument 4 passed to Pecotamic\Sitemap\Models\SitemapEntry::__construct() must be of the type float or null, object given, called in /home/forge/www-staging.domain.com/vendor/pecotamic/sitemap/src/Models/Sitemap.php on line 48

More info:
```
Statamic 3.1.1 Pro
Laravel 7.30.4
PHP 7.4.10
4rn0/statamic-v3-image-optimizer 1.0.7
aryehraber/statamic-captcha 1.4.0
aryehraber/statamic-logbook 2.0.1
optimoapps/statamic-bard-text-align 1.0.2
pecotamic/sitemap 1.2.0
rias/statamic-redirect 1.4.3
```

**Comment by werner-freytag** [comment]
Fixed in release 1.2.1
