### ISSUE TITLE
Is it good practice to list all multisite entries in the same file?

### ISSUE THREAD

**Issue by stuartcusackie** [pecotamic/sitemap#9]
Hi, great package! Saved me a lot of work.

I just noticed the sitemap.xml contains all multisite entries, regardless of what domain I am currently viewing. I would have thought that each domain's sitemap.xml would only list the localised entries for that domain.

It might be fine but I'm just wondering if this is good practice and will it cause problems for webmaster tools?

**Comment by werner-freytag** [comment]
I did some quick research and apparently a sitemap is actually supposed to have only the URLs of a single domain. So I will correct that in an update.

**Comment by werner-freytag** [comment]
Thanks! 🙂  

By the way: You can also define a filter in the `config/pecotamic/sitemap.php` file - if you haven't already done so!

**Comment by werner-freytag** [comment]
Added fix in new release 1.2.3
